name: CI
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - distcheck
          - dist-linux-amd64
          - dist-darwin-amd64

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build yatr
        run: go build -x -v ./cmd/yatr

      - name: Run yatr
        env:
          CGO_ENABLED: "0"
          TARGET: "${{ matrix.target }}"
          DISTFILES_URL: "${{ secrets.DISTFILES_URL }}"
        run: ./yatr
