name: CI
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - distcheck
          - dist-linux-amd64
          - dist-darwin-amd64

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build yatr
        env:
          GO111MODULE: on
        run: go build -x -v ./cmd/yatr

      - name: Run yatr
        env:
          CGO_ENABLED: 0
          TARGET: {{ matrix.target }}
        run: ./yatr
